config/routes.rb
Rails.application.routes.draw do
  resources :badges, only: :index
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'tests#index'
  get '/admin' => 'admin/tests#index', as: :admin_root

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'sessions'}

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    resources :gists, only: :create
    member do
      get :result
    end
  end

  namespace :admin do
    resources :badges, shallow: true
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, except: :index, shallow: true do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: %i[index]
  end
end

app/models/badge.rb
class Badge < ApplicationRecord

  enum rules: {
    first_try: 0 ,
    all_of_level: 1,
    all_from_category: 2
  }.freeze
  
  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :name, presence: true
  validates :rule, presence: true
  validates :img_url, presence: true, :format => { :with => %r{\.(jpg|png)\z}i, }

end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController

  before_action :set_badge, only: %i[edit update destroy show]

  def index
    @badges = Badge.all
  end

  def show; end

  def edit; end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badge_path(@badge)
    else
      render :new
    end
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badge_path(@badge)
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy

    redirect_to admin_badges_path
  end

  private

  def set_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:name, :img_url, :rule, :rule_value)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController

  def index
    @current_user = current_user
    @badges = Badge.all
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
  def achieved?(badge)
    current_user.badges.exists?(badge.id)
  end
end

app/views/admin/badges/_badge.html.erb
<tr>

  <td><%= badge.name %></td>
  <td><%= image_tag badge.img_url, class:"achievement" %></td>
  <td><%= badge.rule %></td>
  <td><%= link_to t('show'), admin_badge_path(badge) %></td>
  <td><%= link_to t('edit'), edit_admin_badge_path(badge) %></td>
  <td><%= link_to t('delete'), admin_badges_path, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge], html: {id:"new_badge"} do |form| %>
  <%= render 'shared/errors', resource: @badge %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :img_url %>
    <%= form.text_field :img_url %>
  </div>

  <div class="field rule-select">
    <%= form.label :rule %>
    <%= form.select :rule, Badge.rules.keys.map { |rule| [Badge.human_attribute_name(rule), rule] } %>
  </div>

  <div class="field">
    <%= form.label :rule_value %>
    <%= form.text_field :rule_value %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/admin/badges/edit.html.erb
<h1><%=t('.title')%></h1>

<%= render 'form', badge: @badge %>

<%= button_to 'Back', admin_badges_path, method: :get %>

app/views/admin/badges/index.html.erb
<p id="notice"><%= notice %></p>

<h1><% t('.badges') %></h1><br>

<%= link_to t('.create_button'), new_admin_badge_path %>

<table class="table">
  <tr>
    <th><%= t('.name') %></th>
    <th><%= t('.img') %></th>
    <th><%= t('.rule') %></th>
    <th colspan="3"></th>
  </tr>


  <%= render @badges %>
</table>

app/views/admin/badges/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

<%= link_to t('back'), admin_badges_path %>

app/views/admin/badges/show.html.erb
<h2>Badge ID:<%= @badge.id %></h2>
<p><%=@badge.name %></p>
<%= image_tag @badge.img_url, class: 'achievement' %>

<%= button_to 'Edit', edit_admin_badge_path(@badge), method: :get %>
<%= button_to 'Back', admin_badges_path, method: :get %>