config/routes.rb
Rails.application.routes.draw do
  resources :badges, only: :index
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'tests#index'
  get '/admin' => 'admin/tests#index', as: :admin_root

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'sessions'}

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    resources :gists, only: :create
    member do
      get :result
    end
  end

  namespace :admin do
    resources :badges, shallow: true
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, except: :index, shallow: true do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: %i[index]
  end
end

app/models/admin.rb
class Admin < User

  validates :first_name, presence: true
  validates :last_name, presence: true

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
    
  scope :correct, -> { where(correct: true) }

  validate :answers_limit, on: :create

  def answers_limit
    errors.add(:base, 'Maximum answers number is 3') if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord

  enum rules: {
    first_try: 0 ,
    all_of_level: 1,
    all_from_category: 2
  }.freeze
  
  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :name, presence: true
  validates :rule, presence: true
  validates :img_url, presence: true, :format => { :with => %r{\.(jpg|png)\z}i, }

end

app/models/category.rb
class Category < ApplicationRecord
    default_scope {order(title: :asc)}
        
    has_many :tests, dependent: :destroy
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
  validates :url, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :test

    has_many :answers, dependent: :destroy
    has_many :test_passages, foreign_key: :current_question_id, dependent: :nullify
    has_many :gists, dependent: :nullify

    validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User', foreign_key: "author_id"

  has_many :questions, dependent: :destroy
  has_many :users, through: :user_tests
  has_many :test_passages
  has_many :users, through: :test_passages

  scope :easy, -> { where(level: 0..1) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }
  scope :with_category, -> (category_pass) { joins(:category)
                                        .where({ categories: { title: category_pass}})}
  validates :title, presence: true
  validates :title, uniqueness: {scope: :level}
  validates :level, numericality: {only_integer: true, greater_than_or_equal: 0}
  validates :timer, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  
  def self.names_by_category(category)
    with_category(category).order(title: :desc).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_update :set_next_question

  SUCCESS_RATE = 85.0

  def current_question_number
    test.questions.order(:id).where('id <= ?', current_question.id).count
  end

  def success?
    test_result >= SUCCESS_RATE
  end

  def test_result
    (correct_questions * 100 / test.questions.count).round(2)
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    self.passed = true if success?
    save!
  end

  def next_question
    questions_left.first
  end

  def completed?
    current_question.nil? || time_over?
  end

  def time_left
    (self.test.timer * 60) - (Time.now - self.created_at) unless time_over?
  end

  private

  def time_over?
    self.created_at - Time.now + self.test.timer * 60 <= 0
  end

  def questions_left
    test.questions.order(:id).where('id > ?', current_question.id)
  end

  def correct_answer?(answer_ids)
    return unless answer_ids
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def set_next_question
    self.current_question = next_question
  end

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answers
    current_question.answers.correct
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  has_many :authored_tests, class_name: 'Test', foreign_key: "author_id" , dependent: :nullify
  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :gists
  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges

  def tests_passed(lvl)
    tests.where(level: lvl)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  def create
    test_passage = TestPassage.find(params[:test_passage_id])
    result = GistQuestionService.new(test_passage.current_question).call

    if result.success?
      Gist.create!(user: current_user, question: test_passage.current_question, url: result.url)
      flash_options = {notice: "#{view_context.link_to(t('.success'), result.url, target: '_blank')}"}
    else
      flash_options = {alert: t('.failure')}
    end
    redirect_to test_passage, flash_options
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

  before_action :authenticate_user!

  def index
    @tests = Test.all
  end

  def start
    @test = Test.find(params[:id])
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Time.current.year
  end

  def github_url(author, repo)
    link_to author, repo, target: :_blank
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
  def achieved?(badge)
    current_user.badges.exists?(badge.id)
  end
end

app/helpers/gists_helper.rb
module GistsHelper
  def question_shortener(question)
    question.body.truncate(25)
  end

  def gist_hash(url)
    url.split('/').last
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    title = question.persisted? ? 'Edit' : 'Create'
    "#{title} #{question.test.title} Question"
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def question_counter
    "#{@test_passage.current_question_number}/#{@test_passage.test.questions.count}"
  end
end

app/helpers/tests_helper.rb
module TestsHelper
  TEST_LEVELS = { 0 => 'easy', 1 => 'elementary', 2 => 'advanced', 3 => 'hard'}

  def test_level(test)
    TEST_LEVELS[test.level] || :hero
  end
end

app/views/admin/_nav.html.erb
<h1><%= link_to t('admin.panel'), admin_root_path %></h1>

<div class="nav nav-admin">
  <span class="nav-admin user"><%= t('admin.panel') %></span>
  <div class="nav-admin user">
    <%= t('welcome') %>
    <b class="nav-admin user-email"><%= current_user.email %></b>
    <%= link_to t('logout'), destroy_user_session_path, method: :delete %>
  </div>
</div>
<%= button_to t('view_badges_button'), admin_badges_path, method: :get %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Admin Panel | TestGuru</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
  <body>
  <%= render 'admin/nav' %>
  <%= render 'shared/flash' %>

  <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestGuru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>

</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.present? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <h2>Errors detected </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :p, message, class: "flash #{key}" %>
<% end %>

app/views/shared/_footer.html.erb
<div>
  <%= current_year %>
</div>
<div>
  <h2><%= t('author') %></h2><br>
  <p>Никита Сидоров</p>
</div>
<div>
  <div>
    <p><%= t('project') %></p>
    <%= github_url('Test-Guru', 'https://github.com/KebabJoy/Test-Guru/tree/7th_task')%>
  </div>
  <div>
    <%= link_to t('link'), "thinknetica.com", target: :_blank %>  <!--можно в хэлпер засунуть, но в задании этого не сказано-->
    <p><%= t('link_description') %></p>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="header">
  <div class="project_name">
    <h1><%= link_to 'Test Guru', root_path %></h1>
  </div>
  <%= render 'shared/flash' %>
  <% if user_signed_in? %>
    <div class="nav user">Welcome, <b><%= current_user.email %></b> Guru
    <%= button_to 'View Badges', badges_path, method: :get %>
     <%= button_to 'Exit', destroy_user_session_path, method: :delete %></div>
  <% end %>
</div>