config/routes.rb
Rails.application.routes.draw do
  resources :badges, only: :index
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'tests#index'
  get '/admin' => 'admin/tests#index', as: :admin_root

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'sessions'}

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    resources :gists, only: :create
    member do
      get :result
    end
  end

  namespace :admin do
    resources :badges, shallow: true
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, except: :index, shallow: true do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: %i[index]
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
    
  scope :correct, -> { where(correct: true) }

  validate :answers_limit, on: :create

  def answers_limit
    errors.add(:base, 'Maximum answers number is 3') if question.answers.count >= 4
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController

  before_action :set_question, only: %i[new create]
  before_action :set_answer, only: %i[show edit update destroy]


  def show; end

  def new
    @answer = @question.answers.new
  end

  def edit; end

  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to admin_answer_path(@answer)
    else
      render :show
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to admin_answer_path(@answer)
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to admin_question_path(@answer.question)
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:title, :correct)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_answer.html.erb
<tr>
  <td>
    <%= answer.title %><br>
  </td>
  <td>
    <%= link_to 'Show', admin_answer_path(answer)%>
  </td>
  <td>
    <%= link_to 'Edit', edit_admin_answer_path(answer)%>
  </td>
  <td>
    <%= link_to 'Delete', admin_answer_path(answer), method: :delete, data: { confirm: 'Are you sure?' } %>
  </td>
</tr>

app/views/admin/answers/_form.html.erb
<%= form_with model: model  do |form| %>
  <%= render 'shared/errors', resource: @answer %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title, id: :answer_title %>
  </p><br>

  <p>
    <%= form.label :correct %>
    <%= form.check_box :correct, id: :answer_correct %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/admin/answers/edit.html.erb
<h1><%= t('.title') %></h1>

<h2>Question: <%= @answer.question.body %></h2>

<%= render 'form', model: [:admin,@answer] %>
<%= link_to t('back'), admin_question_path(@answer.question) %>

app/views/admin/answers/new.html.erb
<h1>New Answer</h1>

<p>
  <%= @question.body %>
</p>

<%= render 'form', model: [:admin,@question, @answer] %>
<%= link_to 'Back', admin_question_path(@question) %>

app/views/admin/answers/show.html.erb
<h1><%= t('.question')%></h1>

<p>
  <%= @answer.question.body %>
</p>

<p>
  <b>Ответ:</b>
  <%= @answer.title %>
</p>

<p>
  <b><%= t('.correctness') %></b>
  <%= @answer.correct ? "True" : "False" %>
</p>

<%= link_to t('.edit'), edit_admin_answer_path(@answer) %> |
<%= link_to t('back'), admin_question_path(@answer.question) %>