config/routes.rb
Rails.application.routes.draw do
  resources :badges, only: :index
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'tests#index'
  get '/admin' => 'admin/tests#index', as: :admin_root

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'sessions'}

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    resources :gists, only: :create
    member do
      get :result
    end
  end

  namespace :admin do
    resources :badges, shallow: true
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, except: :index, shallow: true do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :gists, only: %i[index]
  end
end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :test

    has_many :answers, dependent: :destroy
    has_many :test_passages, foreign_key: :current_question_id, dependent: :nullify
    has_many :gists, dependent: :nullify

    validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController

  before_action :set_test, only: %i[create new]
  before_action :set_question, only: %i[show destroy edit update]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def edit; end

  def show
    @answers = @question.answers
  end

  def new
    @question = @test.questions.new
  end

  def create
    @question = @test.questions.new(question_params)

    if @question.save
      redirect_to admin_question_path(@question)
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to admin_question_path(@question)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to admin_test_path(@question.test)
  end

  private

  def question_params
    params.require(:question).permit(:body)
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def set_test
    @test = Test.find(params[:test_id])
  end

  def rescue_with_question_not_found
    render plain: "Such test was not found"
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    title = question.persisted? ? 'Edit' : 'Create'
    "#{title} #{question.test.title} Question"
  end
end

app/views/admin/questions/_form.html.erb
<%= form_with  model: model do |form| %>
  <%= render 'shared/errors', resource: @question %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_field :body, id: :question_body %>
  </p><br>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/admin/questions/edit.html.erb
<h1><%= question_header(@question) %></h1>
<%= render 'form', model: [:admin,@question] %>
<%= button_to 'Back', admin_test_path(@question),method: :get %>

app/views/admin/questions/new.html.erb
<h1><%= question_header(@question) %></h1>
<%= render 'form', model: [:admin, @test, @question] %>
<%= button_to 'Back', admin_test_path(@test),method: :get %>

app/views/admin/questions/show.html.erb
<h1><%= @question.test.title %> Question </h1>

<div>
  <h2><%= @question.body %></h2><br>
  <%= link_to 'New Answer', new_admin_question_answer_path(@question) %>
  <table border="1">
    <tr>
      <th>Answer ID:</th>
      <th>Body: </th>
      <th>Edit: </th>
      <th>Delete: </th>
    </tr>
    <%= render @question.answers %>
  </table>
</div>


<%= link_to 'Edit Question', edit_admin_question_path(@question) %>
<%= link_to 'Back', admin_test_path(@question.test) %>